### ISSUE TITLE
Linux/macOS support?

### ISSUE THREAD

**Issue by solinium** [EldinZenderink/LittleWeeb#1]
More of a question than an issue, but are you planning on linux/macOS support? All of the current things you're using should be compatible. I'd be willing to make a few pull requests to help.

**Comment by EldinZenderink** [comment]
I would love to, especially since my NAS runs  on Linux. But with the limited amount of time that I have I am not really sure if I am able to make it fully working, besides that I would have to program two different versions every time that I finish a new release. This is due to how file systems differ on both operating systems. Besides that, I would have to use different commands to open certain processes like chrome, etc. It's not difficult, just time consuming. If you want you can put in a pull request and do it yourself, I would be very happy!
