### ISSUE TITLE
Unable to run LittleWeeb Client under Ubuntu 18.04

### ISSUE THREAD

**Issue by KRDucky** [EldinZenderink/LittleWeeb#18]
When running with sudo mono LittleWeeb.exe, this appears:

Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

I have stacktrace in the debug output too. 

Have you considered building a Flatpak or AppImage file for the program? That is a self contained, working program file that contains all necessary software.

**Comment by EldinZenderink** [comment]
First, you are trying to run the mono version of specific windows build version that only runs on windows through the .Net framework (thus not mono) due to using WinForms i.c.m. CefSharp (which is windows only).  

You could use LittleWeebServer and run that, which is the console version where  you need to run the interface through a browser of choice on the same machine. 

That said, the server is not really.... well how should I put it: In working condition.

Luckily, I dont like to have a separate server version for linux or any other platform, so I went ahead and started messing with ElectronNet (the Net wrapper for electron). This was after that I reworked the whole code base to support C# .Net Core 2.1 which means its cross platform by default and does not require mono. 

In the end, I got it working yesterday (little teaser ;) ): 

![](https://i.imgur.com/y73oBrz.png)

But I am certainly not a linux expert, and there are quite some issues to be fixed to put this version online, although I have a deadline for within two days. 

Until then, good luck!

**Comment by EldinZenderink** [comment]
Hi, version 0.4.0 has been released for most platforms: https://littleweeb.github.io/ or https://github.com/littleweeb/Desktop, should fix the issues you were having entirely ;)
