### ISSUE TITLE
Threat detected by Avast.

### ISSUE THREAD

**Issue by karkinissan** [EldinZenderink/LittleWeeb#2]
Avast said the file has the threat idp.generic. I added it to the exception in mine but you should look into it.

**Comment by EldinZenderink** [comment]
Had no issue with the default windows virus scanner, and according to virustotal, I am not doing something weird: https://www.virustotal.com/#/file/e4c8138d4a7dbf99e64cbeac255c3e5a9d5eb332851ac3a556928ccaaad837ce/details.

**Comment by karkinissan** [comment]
Probably a false positive on my end then.  
Thanks for looking into it.  
LOVE this project. 1080p Nichijou releases here I come.

**Comment by EldinZenderink** [comment]
No problem, didn't have time to write a proper response, My guess is that Avast thinks this application acts like some kind of virus/malware,  I guess because it opens chrome automatically when you launch it. + It uses a tcp connection for the irc xdcc part, so yeah, think that's whats triggering the false positive. I hope the application is helpfull :D have fun watching!
