### ISSUE TITLE
Cannot find all files that Nibl finds

### ISSUE THREAD

**Issue by m4st3rP** [EldinZenderink/LittleWeeb#5]
I wanted to download Net-juu no Susume in 1080p but couldn't find it even though it is on the same bots as the 720p versions. (https://nibl.co.uk/bots.php?search=Net-juu+no+Susume+1080)
Also I couldn't find the Scum relase of Shoujo Shuumatsu Ryokou (https://nibl.co.uk/bots.php?search=scum+shoujo) and the Asenshi Release of Children of the Whales (https://nibl.co.uk/bots.php?search=asenshi+Kujira+no+Kora).

**Comment by EldinZenderink** [comment]
Hi,
I am aware of the issues with the searching for anime. This is due to the fact that some episodes/seasons are named using different methods per release group. For example... Fate Zero has 2 seasons... but almost all the releasers just continued the episode count from 1 to 25 instead of like Fate/Zero s2 e1. etc. 

This is like a never ending battle, and I probably should just think about adding a seperate Nibl search only method (like in the first few versions) because it's never going to be perfect ;X. 

That said, I am working on improving things, but I am a bit short on time so it might take a weekend to finish. (or more, not really sure when life starts knocking on the door ;( )

Anyway, so far Net-juu seems to be working again: 
![image](https://user-images.githubusercontent.com/12187560/32610821-321a1496-c564-11e7-9ee6-a860f845230e.png)

Scum releases of Shoujou: 
![image](https://user-images.githubusercontent.com/12187560/32610911-773f4028-c564-11e7-8912-e6987e19d85f.png)

And the ashenshi release of children of the whales: 
![image](https://user-images.githubusercontent.com/12187560/32610988-aa87bea6-c564-11e7-947a-defe4d90f5f4.png)

Thanks anyways for reporting these! I can't check all existing anime in the world so these are a huge help :D. 

Look forward to the new version, it contains a few new features as well :)

Sneek peek : 
![image](https://user-images.githubusercontent.com/12187560/32611093-f4c7e37e-c564-11e7-9ea4-1e744841812c.png)

Playing with the interface a bit, still needs some work tho ^^.

**Comment by m4st3rP** [comment]
Allright. Seperate Nibl search only sounds good and the sneek peek also looks nice.

**Comment by ewasion** [comment]
You could try using [https://github.com/erengy/anime-relations](this).

**Comment by EldinZenderink** [comment]
That's awesome :D will definitely consider using it and contributing to it as well :D.
